version: "3.9"


services:
  api:
    build:
      context: ..
      dockerfile: docker/DockerFile.dev
    ports:
      - "8000:8000"
    environment:
      - LOG-LEVEL=DBUG
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../:/app
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
